---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeprj.github.io
  resources:
  - databaseaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeprj.github.io
  resources:
  - databaseaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - kubeprj.github.io
  resources:
  - databaseaccounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubeprj.github.io
  resources:
  - events
  verbs:
  - create
  - patch
