---
apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: psqladmin.cwx.io/v1
    kind: DatabaseAccountControllerConfig
    metadata:
      name: "controller-config"
    dsn: "postgres://postgres:mysecretpassword@localhost:5432/"
kind: ConfigMap
metadata:
  name: k8s-psql-operator-manager-config
  namespace: k8s-psql-operator-system
